name: Azure VM Deployment

on: 
    workflow_dispatch:
      inputs:
        environment:
          description: 'Environment'
          required: true
          default: develop
          type: choice
          options:
          - develop
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Determine IP address based on environment
      id: set-ip
      run: |
        if [ "${{ github.event.inputs.environment }}" == "develop" ]; then
          echo "IP_ADDRESS=172.191.162.233" >> $GITHUB_ENV
        elif [ "${{ github.event.inputs.environment }}" == "production" ]; then
          echo "IP_ADDRESS=172.191.162.233" >> $GITHUB_ENV
        else
          echo "Invalid environment specified"
          exit 1
        fi

    - name: Connect to Azure VM
      run: ssh -o StrictHostKeyChecking=no azureuser@${{ env.IP_ADDRESS }} "echo Connected successfully"

    - name: Pull Docker image
      run: ssh -o StrictHostKeyChecking=no azureuser@${{ env.IP_ADDRESS }} "sudo docker pull nadine2001/mp-devops:latest"

    - name: Run Docker container
      run: ssh -o StrictHostKeyChecking=no azureuser@${{ env.IP_ADDRESS }} "sudo docker run -p 3000:3000 -d nadine2001/mp-devops:latest"
