name: Terraform Apply

on:
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init ./terraform

      - name: Terraform Apply
        run: |
          cd ./terraform
          terraform apply -auto-approve
